name: Azure ACR Login

inputs:
  client-id:
    type: string
    required: true

  tenant-id:
    type: string
    required: true

  subscription-id:
    type: string
    required: true

  registry:
    type: string
    required: true
    
runs:
  using: composite
  steps:
    - name: Login to Azure with OIDC
      uses: azure/login@v3
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}

    - name: Login to Azure Container Registry
      shell: bash
      env:
        IMAGE_REGISTRY: ${{ inputs.registry }}
      run: az acr login --name "${IMAGE_REGISTRY%%.*}"
