name: Template.Deployables.Build

on:
  workflow_call:
    inputs:
      matrix-json:
        description: '[{ build, name, context, dockerfilePath, proposedImage }]'
        required: true
        type: string
      has-matrix-json:
        required: true
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: ${{ matrix.buildable.name }}
    if: ${{ inputs.has-matrix-json == true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildable: ${{ fromJSON(inputs.matrix-json) }}
    steps:
      - uses: actions/checkout@v7

      - shell: pwsh
        env:
          VALUE: ${{ vars.AZURE_CLIENT_ID }}
        run: Write-Host "$env:VALUE"

      - id: login
        name: Azure Container Registry Login
        uses: nixonjoshua98/shared-workflows/.github/actions/azure-acr-login@feature/speed-improvements
        background: true
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUB_ID }}
          registry: ${{ vars.AZURE_REGISTRY }}

      - uses: docker/setup-buildx-action@v4

      - name: Build ${{ matrix.buildable.name }}
        uses: docker/build-push-action@v7
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.buildable.context }}
          file: ${{ matrix.buildable.dockerfilePath }}
          tags: ${{ matrix.buildable.proposedImage }}

      - name: Azure Container Registry Login
        wait: login

      - name: Push ${{ matrix.buildable.name }}
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ matrix.buildable.proposedImage }}