name: Template.Pipeline.Build

on:
  workflow_call:
    inputs:
      matrix-json:
        type: string
        required: true

      should-run:
        type: boolean
        required: true

      sparse-checkout:
        type: string
        default: ''

      azure-client-id:
        required: true
        type: string

      azure-tenant-id:
        type: string
        required: true

      azure-subscription-id:
        type: string
        required: true

      azure-registry:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build ${{ matrix.project.name }}
    if: ${{ inputs.should-run }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(inputs.matrix-json) }}
    steps:

      - parallel:
        - uses: actions/checkout@v7
          with:
            sparse-checkout: ${{ inputs.sparse-checkout }}

        - uses: docker/setup-buildx-action@v4

        - name: Login to Azure
          uses: nixonjoshua98/shared-workflows/.github/actions/azure-acr-login@v1.6
          with:
            client-id: ${{ inputs.azure-client-id }}
            tenant-id: ${{ inputs.azure-tenant-id }}
            subscription-id: ${{ inputs.azure-subscription-id }}
            registry: ${{ inputs.azure-registry }}

      - name: Build ${{ matrix.project.name }}
        uses: docker/build-push-action@v7
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.project.context }}
          file: ${{ matrix.project.dockerfilePath }}
          tags: ${{ matrix.project.imageName }}

      - name: Build ${{ matrix.project.name }}
        uses: docker/build-push-action@v7
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.project.context }}
          file: ${{ matrix.project.dockerfilePath }}
          tags: ${{ matrix.project.imageName }}
          outputs: type=tar,dest=/tmp/${{ matrix.project.imageName }}.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.project.imageName }}
          path: /tmp/${{ matrix.project.imageName }}.tar
          retention-days: 1