name: Template.Deployables.Setup

on:
  workflow_call:
    inputs:
      deployables-json:
        description: '[{ name, build }]'
        required: true
        type: string

      environments-json:
        description: '[{ name, deploy }]'
        required: true
        type: string

    outputs:
      test-projects-json:
        value: ${{ jobs.setup.outputs.test-projects-json }}

      environments-json:
        value: ${{ jobs.setup.outputs.environments-json }}

      buildable-json:
        value: ${{ jobs.setup.outputs.buildable-json }}

      has-any-testable:
        value: ${{ jobs.setup.outputs.has-any-testable }}

      has-any-buildable:
        value: ${{ jobs.setup.outputs.has-any-buildable }}

      has-any-deployable:
        value: ${{ jobs.setup.outputs.has-any-deployable }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-projects-json: ${{ steps.metadata.outputs.test-projects-json }}
      has-any-testable: ${{ steps.metadata.outputs.has-any-testable }}
      environments-json: ${{ steps.metadata.outputs.environments-json }}
      buildable-json: ${{ steps.metadata.outputs.buildable-json }}
      has-any-buildable: ${{ steps.metadata.outputs.has-any-buildable }}
      has-any-deployable: ${{ steps.metadata.outputs.has-any-deployable }}
    steps:
      - name: Checkout .github
        uses: actions/checkout@v7
        with:
          sparse-checkout: |
            .github

      - name: Checkout required resources
        uses: actions/checkout@v7
        with:
          repository: nixonjoshua98/shared-workflows
          ref: v1.5
          path: _shared
          sparse-checkout: |
            .github/scripts/CreateDeployableMeta.ps1

      - name: Get files changed
        id: changed
        uses: tj-actions/changed-files@v47
        with:
          json: true
          
      - name: Create json data
        id: metadata
        shell: pwsh
        env:
          GITHUB_SHA_VALUE: ${{ github.sha }}
          AZURE_REGISTRY: ${{ vars.AZURE_REGISTRY }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          DEPLOYABLES_JSON: ${{ inputs.deployables-json }}
          ENVIRONMENTS_JSON: ${{ inputs.environments-json }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          CHANGED_FILES_JSON: ${{ steps.changed.outputs.all_changed_files }}
        run: |
          function Write-Env($name, $value) {
            "$name=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

          # Filter out the environments which are not beng deployed to
          # The output looks like [ { name: string } ] - It being empty is possible

          $environments     = @( $env:ENVIRONMENTS_JSON | ConvertFrom-Json | Where-Object { $_.deploy } )
          $environmentsJson = ConvertTo-Json -InputObject ([object[]]$environments) -Compress

          Write-Env "environments-json" $environmentsJson

          # Grab all the metadata needed, we have this in a seperate script so its easier to work with.

          $metadataJson = & _shared/.github/scripts/CreateDeployableMeta.ps1 `
            -DeployablesJson    $env:DEPLOYABLES_JSON `
            -ChangedFilesJson   $env:CHANGED_FILES_JSON `
            -GitHubSHA          $env:GITHUB_SHA_VALUE `
            -GitHubRefName      $env:GITHUB_REF_NAME `
            -ContainerRegistry  $env:AZURE_REGISTRY `
            -GitHubEventName    $env:GITHUB_EVENT_NAME

          $metadata = @( $metadataJson | ConvertFrom-Json )

          # Filter the project metadata so that we only return the projects which are being built.
          # Additional bits of metadata include test projects, paths, docker build context etc.

          $buildableMetadata  = @( $metadata | Where-Object { $_.build } )
          $buildableJson      = ConvertTo-Json -InputObject ([object[]]$buildableMetadata) -Compress
          $hasBuildable       = ($buildableMetadata.Count -gt 0).ToString().ToLower()
          $hasAnyDeployable   = (($buildableMetadata.Count -gt 0) -and ($environments.Count -gt 0)).ToString().ToLower()

          Write-Env "buildable-json"      $buildableJson
          Write-Env "has-any-buildable"   $hasBuildable
          Write-Env "has-any-deployable"  $hasAnyDeployable

          # Similar to the buildable json, we create a filtered list of all test projects involed in the workflow

          $testMetadata       = @( $metadata | Where-Object { $_.runTests } )
          $testProjectMatrix  = @( $testMetadata | ForEach-Object { $_.testProjects } | Sort-Object -Property path -Unique )
          $testProjectsJson   = ConvertTo-Json -InputObject ([object[]]$testProjectMatrix) -Compress
          $hasTestProjects    = ($testProjectMatrix.Count -gt 0).ToString().ToLower()

          Write-Env "test-projects-json"      $testProjectsJson
          Write-Env "has-any-testable"  $hasTestProjects