name: Template.Pipeline

# # # # # # # # # #
# Runs through all the provided deployables, and environmentts with each step running in parallel where possible.
# All deployables must succeed the step before moving on, which prevents partial-deployments.
#
# Vars
#   AZURE_SUB_ID
#   AZURE_REGISTRY
#   AZURE_TENANT_ID
#   AZURE_CLIENT_ID
#   GH_GITOPS_REPO
# # # # # # # # # #

on:
  workflow_call:
    inputs:
      environment-json:
        type: string
        default: '[]'

      buildable-json:
        type: string
        default: '[]'

      sparse-checkout:
        type: string
        default: ''

      azure-client-id:
        type: string
        default: ''

      azure-tenant-id:
        type: string
        default: ''

      azure-subscription-id:
        type: string
        default: ''

      azure-registry:
        type: string
        default: ''

      gitops-repository:
        type: string
        default: ''

      deploy-action:
        type: string
        default: ''

      enable-trivy:
        type: boolean
        default: false

    secrets:
      GITOPS_REPO_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    uses: ./.github/workflows/Template.Pipeline.Setup.yaml
    with:
      buildable-json: ${{ inputs.buildable-json }}
      environment-json: ${{ inputs.environment-json }}
      azure-registry: ${{ inputs.azure-registry || vars.AZURE_REGISTRY }}

  test:
    needs: 
      - setup
    uses: ./.github/workflows/Template.Pipeline.Tests.yaml
    with:
      sparse-checkout: ${{ inputs.sparse-checkout }}
      matrix-json: ${{ needs.setup.outputs.test-projects-json }}
      should-run: ${{ needs.setup.outputs.has-any-testable == 'true' }}

  build:
    needs:
      - setup
    uses: ./.github/workflows/Template.Pipeline.Build.yaml
    with:
      sparse-checkout: ${{ inputs.sparse-checkout }}
      matrix-json: ${{ needs.setup.outputs.buildable-json }}
      should-run: ${{ needs.setup.outputs.has-any-buildable == 'true' }}
      enable-trivy: ${{ inputs.enable-trivy }}
      azure-client-id: ${{ inputs.azure-client-id || vars.AZURE_CLIENT_ID }}
      azure-tenant-id: ${{ inputs.azure-tenant-id || vars.AZURE_TENANT_ID }}
      azure-subscription-id: ${{ inputs.azure-subscription-id || vars.AZURE_SUB_ID }}
      azure-registry: ${{ inputs.azure-registry || vars.AZURE_REGISTRY }}

  deploy:
    needs:
      - setup
      - test
      - build
    if: |
      !cancelled() && 
      !failure() && 
      !contains(needs.*.result, 'failure') && 
      !contains(needs.*.result, 'cancelled') &&  
      needs.setup.outputs.has-any-deployable == 'true'
    uses: ./.github/workflows/Template.Pipeline.Deploy.yaml
    with:
      deploy-action: ${{ inputs.deploy-action }}
      gitops-repository: ${{ inputs.gitops-repository || vars.GH_GITOPS_REPO }}
      matrix-json: ${{ needs.setup.outputs.buildable-json }}
      environment-json: ${{ needs.setup.outputs.environment-json }}
    secrets:
      GITOPS_REPO_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}