name: Template.Pipeline.Deploy

on:
  workflow_call:
    inputs:
      matrix-json:
        type: string
        required: true

      environment-json:
        type: string
        default: '[]'

      gitops-repository:
        type: string
        required: true

    secrets:
      GITOPS_REPO_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  dispatch:
    name: Deploy ${{ matrix.deployable.name }} ( ${{ matrix.environment.name }} )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployable: ${{ fromJSON(inputs.matrix-json) }}
        environment: ${{ fromJSON(inputs.environment-json) }}
    steps:
      - name: Create Payload
        id: payload
        shell: pwsh
        env:
          IMAGE: ${{ matrix.deployable.imageName }}
          ENVIRONMENT: ${{ matrix.environment.name }}
        run: |
          $payload = @{
            image         = $env:IMAGE
            environment   = $env:ENVIRONMENT
          } | ConvertTo-Json -Compress

          "payload=$payload" >> $env:GITHUB_OUTPUT

      - uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          repository: ${{ inputs.gitops-repository }}
          event-type: ${{ matrix.deployable.eventName }}
          client-payload: ${{ steps.payload.outputs.payload }}