name: Template.Deployables.Dispatch

on:
  workflow_call:
    inputs:
      matrix-json:
        description: '[{ name, proposedImage }]'
        required: true
        type: string

      environments-json:
        description: '[{ name, deploy }]'
        type: string
        default: '[]'

    secrets:
      GITOPS_REPO_PAT:
        required: true

permissions:
  contents: read

jobs:
  dispatch:
    name: Dispatch ${{ matrix.deployable.name }} ( ${{ matrix.environment.name }} )
    if: ${{ matrix.environment.deploy == true }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        deployable: ${{ fromJSON(inputs.matrix-json) }}
        environment: ${{ fromJSON(inputs.environments-json) }}
    steps:
      - name: Dispatch image change
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITOPS_REPO_PAT }}
          repository: nixonjoshua98/nixon-gitops
          event-type: ${{ matrix.deployable.eventName }}
          client-payload: >-
            {
              "image": "${{ matrix.deployable.proposedImage }}",
              "environment": "${{ matrix.environment.name }}"
            }