name: Template.Deployables.Tests

on:
  workflow_call:
    inputs:
      matrix-json:
        description: '[{ name, path }]'
        required: true
        type: string

      should-run:
        required: true
        type: boolean

      sparse-checkout:
        type: string
        default: ''

permissions:
  contents: read

jobs:
  test:
    name: Test ${{ matrix.project.name }}
    if: ${{ inputs.should-run == true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(inputs.matrix-json) }}
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: ${{ inputs.sparse-checkout }}

      - name: Test ${{ matrix.project.name }}
        shell: bash
        run: dotnet test '${{ matrix.project.path }}'