name: Template.Pipeline.Build

on:
  workflow_call:
    inputs:
      matrix-json:
        type: string
        required: true

      should-run:
        type: boolean
        default: true

      sparse-checkout:
        type: string
        default: ''

      azure-client-id:
        type: string
        required: true

      azure-tenant-id:
        type: string
        required: true

      azure-subscription-id:
        type: string
        required: true

      azure-registry:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build ${{ matrix.project.name }}
    if: ${{ inputs.should-run }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(inputs.matrix-json) }}
    steps:

      - parallel:
        - uses: actions/checkout@v7
          with:
            sparse-checkout: ${{ inputs.sparse-checkout }}

        - uses: docker/setup-buildx-action@v4

        - name: Login to Azure with OIDC
          uses: azure/login@v3
          with:
            client-id: ${{ inputs.azure-client-id }}
            tenant-id: ${{ inputs.azure-tenant-id }}
            subscription-id: ${{ inputs.azure-subscription-id }}

      - name: Login to Azure Container Registry
        shell: bash
        env:
          IMAGE_REGISTRY: ${{ inputs.azure-registry }}
        run: az acr login --name "${IMAGE_REGISTRY%%.*}"

      - name: Build ${{ matrix.project.name }}
        uses: docker/build-push-action@v7
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.project.context }}
          file: ${{ matrix.project.dockerfilePath }}
          tags: ${{ matrix.project.imageName }}