name: Template.Deployables.Run

on:
  workflow_call:
    inputs:
      environments-json:
        type: string
        default: '[]'

      deployables-json:
        type: string
        required: true

      sparse-checkout:
        type: string
        default: ''

      azure-client-id:
        required: true
        type: string

      azure-tenant-id:
        required: true
        type: string

      azure-subscription-id:
        required: true
        type: string

      azure-registry:
        required: true
        type: string

      gitops-repository:
        required: false
        type: string

    secrets:
      GITOPS_REPO_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    uses: ./.github/workflows/Template.Deployables.Setup.yaml
    with:
      deployables-json: ${{ inputs.deployables-json }}
      environments-json: ${{ inputs.environments-json }}
      azure-registry: ${{ inputs.azure-registry }}

  test:
    needs: 
      - setup
    uses: ./.github/workflows/Template.Deployables.Tests.yaml
    with:
      sparse-checkout: ${{ inputs.sparse-checkout }}
      matrix-json: ${{ needs.setup.outputs.test-projects-json }}
      should-run: ${{ needs.setup.outputs.has-any-testable == 'true' }}

  build:
    needs:
      - setup
    uses: ./.github/workflows/Template.Deployables.Build.yaml
    with:
      sparse-checkout: ${{ inputs.sparse-checkout }}
      matrix-json: ${{ needs.setup.outputs.buildable-json }}
      should-run: ${{ needs.setup.outputs.has-any-buildable == 'true' }}
      azure-client-id: ${{ inputs.azure-client-id }}
      azure-tenant-id: ${{ inputs.azure-tenant-id }}
      azure-subscription-id: ${{ inputs.azure-subscription-id }}
      azure-registry: ${{ inputs.azure-registry }}

  scan:
    needs:
      - setup
      - build
    uses: ./.github/workflows/Template.Deployables.Scan.yaml
    with:
      matrix-json: ${{ needs.setup.outputs.buildable-json }}
      should-run: ${{ needs.setup.outputs.has-any-buildable == 'true' }}
      azure-client-id: ${{ inputs.azure-client-id }}
      azure-tenant-id: ${{ inputs.azure-tenant-id }}
      azure-subscription-id: ${{ inputs.azure-subscription-id }}
      azure-registry: ${{ inputs.azure-registry }}

  deploy:
    needs:
      - setup
      - test
      - build
      - scan
    if: |
      !cancelled() && 
      !failure() && 
      !contains(needs.*.result, 'failure') && 
      !contains(needs.*.result, 'cancelled') &&  
      needs.setup.outputs.has-any-deployable == 'true'
    uses: ./.github/workflows/Template.Deployables.Deploy.yaml
    with:
      gitops-repository: ${{ inputs.gitops-repository }}
      matrix-json: ${{ needs.setup.outputs.buildable-json }}
      environments-json: ${{ needs.setup.outputs.environments-json }}
    secrets:
      GITOPS_REPO_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}