name: Template.Pipeline.Scan

on:
  workflow_call:
    inputs:
      matrix-json:
        required: true
        type: string

      should-run:
        required: true
        type: boolean

      azure-client-id:
        required: true
        type: string

      azure-tenant-id:
        required: true
        type: string

      azure-subscription-id:
        required: true
        type: string

      azure-registry:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  scan:
    name: Scan ${{ matrix.project.name }}
    if: ${{ inputs.should-run == true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(inputs.matrix-json) }}
    steps:
      - name: Azure Container Registry Login
        uses: nixonjoshua98/shared-workflows/.github/actions/azure-acr-login@v1.6
        with:
          client-id: ${{ inputs.azure-client-id }}
          tenant-id: ${{ inputs.azure-tenant-id }}
          subscription-id: ${{ inputs.azure-subscription-id }}
          registry: ${{ inputs.azure-registry }}

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ matrix.project.imageName }}
          scanners: vuln
          format: table
          output: trivy-table.json
          exit-code: '1'
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Publish Trivy Results
        if: always()
        run: |
          if [ -s trivy-table.md ]; then
            echo "## Trivy Scan summary" >> $GITHUB_STEP_SUMMARY
            cat trivy-results.md >> $GITHUB_STEP_SUMMARY
            echo "<hr>" >> $GITHUB_STEP_SUMMARY
          fi
