name: Template.DotNet.Test

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      test-project:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.test-project }}
        working-directory: ${{ inputs.working-directory }}

      - name: Build project
        run: dotnet build ${{ inputs.test-project }} --configuration Release --no-restore
        working-directory: ${{ inputs.working-directory }}

      - name: Run tests
        run: dotnet test ${{ inputs.test-project }} --configuration Release --no-build
        working-directory: ${{ inputs.working-directory }}
