name: Template.Pipeline.Scan

on:
  workflow_call:
    inputs:
      matrix-json:
        required: true
        type: string

      should-run:
        required: true
        type: boolean

      azure-client-id:
        required: true
        type: string

      azure-tenant-id:
        required: true
        type: string

      azure-subscription-id:
        required: true
        type: string

      azure-registry:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  scan:
    name: Scan ${{ matrix.project.name }}
    if: inputs.should-run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(inputs.matrix-json) }}
    steps:
      - name: Login to Azure with OIDC
        uses: azure/login@v3
        with:
          client-id: ${{ inputs.azure-client-id }}
          tenant-id: ${{ inputs.azure-tenant-id }}
          subscription-id: ${{ inputs.azure-subscription-id }}

      - name: Login to Azure Container Registry
        shell: bash
        env:
          IMAGE_REGISTRY: ${{ inputs.azure-registry }}
        run: az acr login --name "${IMAGE_REGISTRY%%.*}"

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ matrix.project.imageName }}
          scanners: vuln
          format: table
          output: trivy-report.txt
          exit-code: '1'
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Publish Trivy Results
        if: always()
        run: |
          if [ -s trivy-report.txt ]; then
            echo "## Trivy Scan summary" >> $GITHUB_STEP_SUMMARY
            echo '```text' >> $GITHUB_STEP_SUMMARY
            cat trivy-report.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
