name: Template.Deployables.Run

on:
  workflow_call:
    inputs:
      environments-json:
        type: string
        default: '[]'

      deployables-json:
        type: string
        required: true

      sparse-checkout:
        type: string
        default: ''

      gitops-repository:
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    uses: ./.github/workflows/Template.Deployables.Setup.yaml
    with:
      deployables-json: ${{ inputs.deployables-json }}
      environments-json: ${{ inputs.environments-json }}

  test:
    needs: 
      - setup
    uses: ./.github/workflows/Template.Deployables.Tests.yaml
    with:
      sparse-checkout: ${{ inputs.sparse-checkout }}
      matrix-json: ${{ needs.setup.outputs.test-projects-json }}
      has-matrix-json: ${{ needs.setup.outputs.has-test-projects-json == 'true' }}

  build:
    needs:
      - setup
    uses: ./.github/workflows/Template.Deployables.Build.yaml
    with:
      sparse-checkout: ${{ inputs.sparse-checkout }}
      matrix-json: ${{ needs.setup.outputs.buildable-json }}
      has-matrix-json: ${{ needs.setup.outputs.has-buildable-json == 'true' }}

  # scan:
  #   needs:
  #     - setup
  #     - build
  #   uses: ./.github/workflows/Template.Deployables.Scan.yaml
  #   with:
  #     matrix-json: ${{ needs.setup.outputs.buildable-json }}
  #     has-matrix-json: ${{ needs.setup.outputs.has-buildable-json == 'true' }}

  deploy:
    needs:
      - setup
      - test
      - build
      # - scan
    if: |
      !cancelled() && 
      !failure() && 
      !contains(needs.*.result, 'failure') && 
      !contains(needs.*.result, 'cancelled') &&  
      needs.setup.outputs.has-any-deployable == 'true'
    uses: ./.github/workflows/Template.Deployables.Deploy.yaml
    with:
      gitops-repository: ${{ inputs.gitops-repository }}
      matrix-json: ${{ needs.setup.outputs.buildable-json }}
      environments-json: ${{ needs.setup.outputs.environments-json }}
    secrets: inherit